name: Deploy Quartz Site to DreamHost via FTP

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # or the version Quartz needs

    - name: Install dependencies
      run: npm install

    - name: Build Quartz site
      run: npm run build

    - name: Upload via FTP to DreamHost
      uses: SamKirkland/FTP-Deploy-Action@v4
      with:
        server: ${{ secrets.DREAMHOST_FTP_HOST }}
        username: ${{ secrets.DREAMHOST_FTP_USER }}
        password: ${{ secrets.DREAMHOST_FTP_PASS }}
        local-dir: ./dist  # Change if your build output folder is different
        server-dir: /path/to/your/website/folder  # Update this to your DreamHost site's root folder
        git-ftp-args: --insecure  # Optional: if you need to bypass cert checks