name: Deploy Quartz Site via SFTP

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Copy config & layout
        run: cp quartz.config.ts quartz.layout.ts quartz/

      - name: Install dependencies
        run: npm ci
        working-directory: ./quartz  # Quartz lives here

      - name: Build Quartz site
        run: npx quartz build --directory ../vault
        working-directory: ./quartz  # Build from Quartz folder

      - name: Debug
        run: |
          echo ${{ secrets.FTP_SERVER }}
          echo ${{ secrets.FTP_USERNAME }}
          echo ${{ secrets.FTP_PASSWORD }}

      - name: Deploy via SFTP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          source: "quartz/public/"   # where Quartz outputs static files
          target: "/home/dh_fm8qv6/docs.sublimeplants.com/"  # DreamHost dir for docs.sublimeplants.com
