name: Deploy Quartz Site via SFTP

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Copy config & layout
        run: cp quartz.config.ts quartz.layout.ts quartz/

      - name: Install dependencies
        run: ls && cd quartz && npm i
        working-directory: ./quartz  # Quartz lives here

      - name: Build Quartz site
        run: npx run build --directory ../vault
        working-directory: ./quartz  # Build from Quartz folder

      - name: Deploy via SFTP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          source: "quartz/public/*"   # where Quartz outputs static files
          target: "/path/to/your/site/root"  # DreamHost dir for docs.sublimeplants.com